using EnumGenerators.Common.StringBuilderUtilities;
using EnumGenerators.Constants;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;

namespace EnumGenerators;

[Generator]
public class EnumsGenerator : IIncrementalGenerator
{
    private const int nonSpecifiedMemberValue = -1;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                GenerateEnumAttributeContants.IDENTIFIER,
                predicate: static (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax || syntaxNode is StructDeclarationSyntax,
                transform: static (context, _) => Transform(context));

        context.RegisterSourceOutput(provider.Collect(), GenerateEnums);
    }

    private static EnumRequestInfo Transform(GeneratorAttributeSyntaxContext context)
    {
        var attributeData = context.Attributes[0];

        string enumNamespace = (string)attributeData.ConstructorArguments[0].Value!;
        string enumName = (string)attributeData.ConstructorArguments[1].Value!;
        string elementName = (string)attributeData.ConstructorArguments[2].Value!;
        int explicitMemeberValue = GetExplicitMemeberValue(attributeData);

        return new EnumRequestInfo(
            enumNamespace,
            enumName,
            elementName,
            explicitMemeberValue
        );

        static int GetExplicitMemeberValue(AttributeData attributeData)
        {
            if (attributeData.ConstructorArguments.Length < 4)
                return nonSpecifiedMemberValue;

            return (int)attributeData.ConstructorArguments[3].Value!;
        }
    }

    private static void GenerateEnums(SourceProductionContext context, ImmutableArray<EnumRequestInfo> dataArray)
    {
        int length = dataArray.Length;
        if (length == 0) return;

        var traversedIndexes = new HashSet<int>();
        var explicitMemberIndexes = new HashSet<int>();

        for (int i = 0; i < length; i++)
        {
            if (traversedIndexes.Contains(i)) continue;
            traversedIndexes.Add(i);

            var data0 = dataArray[i];
            var enumWithTheSameIdentifierIndexes = new List<int>();
            string enumIdentifier0 = data0.EnumNamespace + data0.EnumName;
            enumWithTheSameIdentifierIndexes.Add(i);
            if (data0.ExplicitMemeberValue != nonSpecifiedMemberValue)
                explicitMemberIndexes.Add(i);

            for (int j = i + 1; j < length; j++)
            {
                if (traversedIndexes.Contains(j)) continue;

                var data1 = dataArray[j];
                string enumIdentifier1 = data1.EnumNamespace + data1.EnumName;

                if (!enumIdentifier0.Equals(enumIdentifier1)) continue;

                traversedIndexes.Add(j);
                enumWithTheSameIdentifierIndexes.Add(j);
                if (data1.ExplicitMemeberValue != nonSpecifiedMemberValue)
                    explicitMemberIndexes.Add(j);
            }

            GenerateEnum(context, data0.EnumNamespace, data0.EnumName, dataArray, enumWithTheSameIdentifierIndexes, explicitMemberIndexes);
        }
    }

    private static void GenerateEnum(
        SourceProductionContext context,
        string enumNamespace,
        string enumName,
        ImmutableArray<EnumRequestInfo> dataArray,
        List<int> enumWithTheSameIdentifierIndexes,
        HashSet<int> explicitMemberIndexes)
    {
        int memberCount = enumWithTheSameIdentifierIndexes.Count;
        var explicitMemberValues = new HashSet<int>();
        var sb = new CodeStringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"namespace {enumNamespace};");
        sb.AppendLine();

        sb.AppendLine($"public enum {enumName} : {GetEnumUnderlyingTypeFromElementCount(memberCount)}");
        sb.AppendLine("{");
        sb.Indent();

        sb.AppendLine("// Explicit members");
        foreach (int explicitMemberIndex in explicitMemberIndexes)
        {
            var data = dataArray[explicitMemberIndex];
            int explicitMemberValue = data.ExplicitMemeberValue;

            explicitMemberValues.Add(explicitMemberValue);
            sb.AppendLine($"{data.MemberName} = {explicitMemberValue},");
        }
        sb.AppendLine();

        int memberValue = 0;

        for (int i = 0; i < memberCount; i++)
        {
            int index = enumWithTheSameIdentifierIndexes[i];
            if (explicitMemberIndexes.Contains(index)) continue;

            var data = dataArray[index];

            while (explicitMemberValues.Contains(memberValue))
            {
                memberValue++;
            }
            sb.AppendLine($"{data.MemberName} = {memberValue},");
            memberValue++;
        }

        sb.Unindent();
        sb.AppendLine("}");

        context.AddSource($"{enumNamespace}.{enumName}.g.cs", sb.ToString());
    }

    private static string GetEnumUnderlyingTypeFromElementCount(int count)
    {
        return count switch
        {
            <= byte.MaxValue + 1 => "byte",
            <= ushort.MaxValue + 1 => "ushort",
            _ => "uint"
        };
    }
}