using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using UITypeGenerators.Common.StringBuilderUtilities;
using static UITypeGenerators.AttributeConstants;
using static UITypeGenerators.Utilities;

namespace UITypeGenerators;

[Generator]
public sealed partial class BaseUITypeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Always inject the attribute declaration so user projects don't need to define it
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("BaseUITypeAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        // 2. Find the single class decorated with [BaseUIType(...)]
        IncrementalValueProvider<BaseTypeInfo?> baseTypeProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetBaseTypeInfo(ctx))
            .Where(static x => x is not null)
            .Collect()
            .Select(static (items, _) => items.IsEmpty ? null : items[0]);

        // 3. Collect all class symbols in the compilation
        IncrementalValueProvider<ImmutableArray<INamedTypeSymbol>> allClassesProvider = context
            .CompilationProvider
            .Select(static (compilation, _) => CollectAllClasses(compilation));

        // 4. Combine and generate
        context.RegisterSourceOutput(
            baseTypeProvider.Combine(allClassesProvider),
            static (ctx, pair) => Execute(ctx, pair.Left, pair.Right));
    }

    private static void Execute(
        SourceProductionContext ctx,
        BaseTypeInfo? baseInfo,
        ImmutableArray<INamedTypeSymbol> allClasses)
    {
        if (baseInfo is null)
            return;

        // Resolve the base class symbol by fully-qualified name for reliable matching
        var members = allClasses
            .Where(c =>
                !c.IsAbstract &&
                IsDirectOrIndirectSubclass(c, baseInfo.FullyQualifiedName))
            .Select(c => new DerivedMemberInfo(c.Name, GetExplicitValue(c)))
            .OrderBy(m => m.Name, StringComparer.Ordinal)
            .ToImmutableArray();

        if (members.IsEmpty)
        {
            ctx.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    "BUITG001",
                    "No subclasses found",
                    "No concrete subclasses of '{0}' were found; the generated enum will be empty.",
                    "BaseUITypeGenerator",
                    DiagnosticSeverity.Warning,
                    isEnabledByDefault: true),
                Location.None,
                baseInfo.ShortName));
        }

        var source = BuildEnumSource(baseInfo, members);
        ctx.AddSource($"{baseInfo.EnumName}.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string BuildEnumSource(
        BaseTypeInfo baseInfo,
        ImmutableArray<DerivedMemberInfo> members)
    {
        var sb = new CodeStringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrWhiteSpace(baseInfo.Namespace);
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {baseInfo.Namespace}");
            sb.AppendLine("{");
            sb.Indent();
        }

        sb.AppendLine($"public enum {baseInfo.EnumName}");
        sb.AppendLine("{");
        sb.Indent();

        sb.AppendLine("None = 0,");

        for (var i = 0; i < members.Length; i++)
        {
            var member = members[i];
            var underlyingValue = member.ExplicitValue ?? StableHash(member.Name);

            sb.AppendLine($"{member.Name} = {underlyingValue},");
        }

        sb.Unindent();
        sb.AppendLine("}");

        if (hasNamespace)
        {
            sb.Unindent();
            sb.AppendLine("}");
        }

        return sb.ToString();
    }
}