using Microsoft.CodeAnalysis;
using System.Linq;
using static UITypeGenerators.Utilities;

namespace UITypeGenerators;

[Generator]
public class ConcreteUICtrlPartialGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (syntaxNode, _) => IsTargetNode(syntaxNode),
                static (context, _) => GetConcreteUIInfo(context))
            .Collect()
            .SelectMany((myObjects, _) => myObjects.Distinct());

        context.RegisterSourceOutput(provider, Generate);
    }

    private static void Generate(SourceProductionContext context, ConcreteUIInfo concreteUIInfo)
    {
        if (concreteUIInfo.UITypeName == null) return;
        if (concreteUIInfo.ConcreteUICtrlName == null) return;
        if (concreteUIInfo.ConcreteUICtrlNamespace == null) return;

        string sourceCode = $@"// <auto-generated />

namespace {concreteUIInfo.ConcreteUICtrlNamespace}
{{
    public partial class {concreteUIInfo.ConcreteUICtrlName}
    {{
        public override {UITypeContants.IDENTIFIER} GetUIType() => {UITypeContants.IDENTIFIER}.{concreteUIInfo.UITypeName};
    }}
}}";

        context.AddSource($"{concreteUIInfo.ConcreteUICtrlNamespace}.{concreteUIInfo.ConcreteUICtrlName}.g.cs", sourceCode);
    }
}