using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Collections.Immutable;
using UITypeGenerators.StringBuilderUtilities;
using static UITypeGenerators.Utilities;

namespace UITypeGenerators;

[Generator]
public class UITypeEnumGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (syntaxNode, _) => IsTargetNode(syntaxNode),
                transform: static (context, _) => GetConcreteUIInfo(context));

        context.RegisterSourceOutput(provider.Collect(), GenerateUIType);
    }

    private static void GenerateUIType(SourceProductionContext context, ImmutableArray<ConcreteUIInfo> concreteUIInfos)
    {
        int length = concreteUIInfos.Length;
        if (length == 0) return;

        var sb = new CodeStringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();
        sb.AppendLine($"namespace {UITypeContants.NAMESPACE};");
        sb.AppendLine();

        sb.AppendLine($"public enum {UITypeContants.NAME} : {UITypeContants.UDERLYING_TYPE}");
        sb.AppendLine("{");
        sb.Indent();

        sb.AppendLine("None = 0,");

        var hashSet = new HashSet<int>();

        for (int i = 0; i < length; i++)
        {
            var uiInfo = concreteUIInfos[i];
            string elementName = uiInfo.UITypeName;

            int hashCode = elementName.GetHashCode();
            int underlyingValue;

            if (hashSet.Contains(hashCode))
            {
                underlyingValue = uiInfo.FallbackUnderlyingValue;
            }
            else
            {
                hashSet.Add(hashCode);
                underlyingValue = hashCode;
            }

            sb.AppendLine($"{elementName} = {underlyingValue},");
        }

        sb.Unindent();
        sb.AppendLine("}");

        context.AddSource($"UIType.g.cs", sb.ToString());
    }
}