namespace UITypeGenerators;

public static class AttributeConstants
{
    public const string AttributeName = "BaseUITypeAttribute";
    public const string AttributeFullName = "BaseUITypeAttribute";
    public const string ValueAttributeName = "UITypeValueAttribute";
    public const string ValueAttributeFullName = "UITypeValueAttribute";

    // Language-agnostic attribute source injected into the compilation
    public const string AttributeSource = """
        // <auto-generated/>
        using System;

        [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
        internal sealed class BaseUITypeAttribute : Attribute
        {
            public string EnumName { get; }

            public BaseUITypeAttribute(string enumName)
            {
                EnumName = enumName;
            }
        }

        /// <summary>
        /// Assigns an explicit underlying <see langword="int"/> value to the generated
        /// enum member for this derived class.
        /// </summary>
        [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
        internal sealed class UITypeValueAttribute : Attribute
        {
            public int Value { get; }

            public UITypeValueAttribute(int value)
            {
                Value = value;
            }
        }
        """;
}